<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

final class CurrenciesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $timestamp = now();

        $currencies = [
            [
                'currency_code' => 'AED',
                'name' => 'UAE Dirham',
                'local_name' => 'UAE Dirham',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'AFN',
                'name' => 'Afghani',
                'local_name' => 'Afghani',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'ALL',
                'name' => 'Lek',
                'local_name' => 'Lek',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'AMD',
                'name' => 'Armenian dram',
                'local_name' => 'Armenian Dram',
                'flag_emoji' => '🇦🇲',
                'minor_unit' => 2,
                'symbol_prefix' => '֏',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'AOA',
                'name' => 'Angolan kwanza',
                'local_name' => 'Angolan Kwanza',
                'flag_emoji' => '🇦🇴',
                'minor_unit' => 2,
                'symbol_prefix' => 'Kz',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'ARS',
                'name' => 'Argentine peso',
                'local_name' => 'Argentine Peso',
                'flag_emoji' => '🇦🇷',
                'minor_unit' => 2,
                'symbol_prefix' => '$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'AUD',
                'name' => 'Australian dollar',
                'local_name' => 'Australian Dollar',
                'flag_emoji' => '🇦🇺',
                'minor_unit' => 2,
                'symbol_prefix' => '$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'AWG',
                'name' => 'Aruban Florin',
                'local_name' => 'Aruban Florin',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'AZN',
                'name' => 'Azerbaijani manat',
                'local_name' => 'Azerbaijani Manat',
                'flag_emoji' => '🇦🇿',
                'minor_unit' => 2,
                'symbol_prefix' => '₼',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BAM',
                'name' => 'Bosnia and Herzegovina convertible mark',
                'local_name' => 'Convertible Mark',
                'flag_emoji' => '🇧🇦',
                'minor_unit' => 2,
                'symbol_prefix' => 'KM',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BBD',
                'name' => 'Barbados dollar',
                'local_name' => 'Barbados Dollar',
                'flag_emoji' => '🇧🇧',
                'minor_unit' => 2,
                'symbol_prefix' => '$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BDT',
                'name' => 'Taka',
                'local_name' => 'Taka',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BHD',
                'name' => 'Bahraini Dinar',
                'local_name' => 'Bahraini Dinar',
                'flag_emoji' => null,
                'minor_unit' => 3,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BIF',
                'name' => 'Burundi Franc',
                'local_name' => 'Burundi Franc',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BMD',
                'name' => 'Bermudian Dollar',
                'local_name' => 'Bermudian Dollar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BND',
                'name' => 'Brunei Dollar',
                'local_name' => 'Brunei Dollar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BOB',
                'name' => 'Boliviano',
                'local_name' => 'Boliviano',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BRL',
                'name' => 'Brazilian Real',
                'local_name' => 'Brazilian Real',
                'flag_emoji' => '🇧🇷',
                'minor_unit' => 2,
                'symbol_prefix' => 'R$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BSD',
                'name' => 'Bahamian Dollar',
                'local_name' => 'Bahamian Dollar',
                'flag_emoji' => '🇧🇸',
                'minor_unit' => 2,
                'symbol_prefix' => '$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BTN',
                'name' => 'Ngultrum',
                'local_name' => 'Ngultrum',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BWP',
                'name' => 'Pula',
                'local_name' => 'Pula',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BYN',
                'name' => 'Belarusian ruble',
                'local_name' => 'Belarusian Ruble',
                'flag_emoji' => '🇧🇾',
                'minor_unit' => 2,
                'symbol_prefix' => 'Br',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'BZD',
                'name' => 'Belizean Dollar',
                'local_name' => 'Belizean Dollar',
                'flag_emoji' => '🇧🇿',
                'minor_unit' => 2,
                'symbol_prefix' => 'BZ$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'CAD',
                'name' => 'Canadian dollar',
                'local_name' => 'CA Dollar',
                'flag_emoji' => '🇨🇦',
                'minor_unit' => 2,
                'symbol_prefix' => '$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'CDF',
                'name' => 'Congolese Franc',
                'local_name' => 'Congolese Franc',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'CHF',
                'name' => 'Swiss Franc',
                'local_name' => 'Swiss Franc',
                'flag_emoji' => '🇨🇭',
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => 'Rp.',
            ],
            [
                'currency_code' => 'CLP',
                'name' => 'Chilean Peso',
                'local_name' => 'Chilean Peso',
                'flag_emoji' => '🇨🇱',
                'minor_unit' => 0,
                'symbol_prefix' => '$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'CNY',
                'name' => 'Yuan Renminbi',
                'local_name' => 'Yuan Renminbi',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'COP',
                'name' => 'Colombian Peso',
                'local_name' => 'Colombian Peso',
                'flag_emoji' => '🇨🇴',
                'minor_unit' => 2,
                'symbol_prefix' => '$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'CRC',
                'name' => 'Costa Rican Colon',
                'local_name' => 'Costa Rican Colon',
                'flag_emoji' => '🇨🇷',
                'minor_unit' => 2,
                'symbol_prefix' => '₡',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'CUP',
                'name' => 'Cuban Peso',
                'local_name' => 'Cuban Peso',
                'flag_emoji' => '🇨🇺',
                'minor_unit' => 2,
                'symbol_prefix' => '₱',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'CVE',
                'name' => 'Cabo Verde Escudo',
                'local_name' => 'Cabo Verde Escudo',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'CZK',
                'name' => 'Czech crown',
                'local_name' => 'Česká koruna',
                'flag_emoji' => '🇨🇿',
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => 'Kč',
            ],
            [
                'currency_code' => 'DJF',
                'name' => 'Djibouti Franc',
                'local_name' => 'Djibouti Franc',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'DKK',
                'name' => 'Danish krone',
                'local_name' => 'Danish Krone',
                'flag_emoji' => '🇩🇰',
                'minor_unit' => 2,
                'symbol_prefix' => 'kr',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'DOP',
                'name' => 'Dominican Peso',
                'local_name' => 'Dominican Peso',
                'flag_emoji' => '🇩🇴',
                'minor_unit' => 2,
                'symbol_prefix' => 'RD$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'DZD',
                'name' => 'Algerian Dinar',
                'local_name' => 'Algerian Dinar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'EGP',
                'name' => 'Egyptian Pound',
                'local_name' => 'Egyptian Pound',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'ERN',
                'name' => 'Nakfa',
                'local_name' => 'Nakfa',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'ETB',
                'name' => 'Ethiopian Birr',
                'local_name' => 'Ethiopian Birr',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'EUR',
                'name' => 'Euro',
                'local_name' => 'Euro',
                'flag_emoji' => '🇪🇺',
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => '€',
            ],
            [
                'currency_code' => 'FJD',
                'name' => 'Fiji Dollar',
                'local_name' => 'Fiji Dollar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'FKP',
                'name' => 'Falkland Islands pound',
                'local_name' => 'Falkland Islands Pound',
                'flag_emoji' => '🇫🇰',
                'minor_unit' => 2,
                'symbol_prefix' => '£',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'GBP',
                'name' => 'British Pound',
                'local_name' => 'British Pound',
                'flag_emoji' => '🇬🇧',
                'minor_unit' => 2,
                'symbol_prefix' => '£',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'GEL',
                'name' => 'Georgian lari',
                'local_name' => 'Georgian Lari',
                'flag_emoji' => '🇬🇪',
                'minor_unit' => 2,
                'symbol_prefix' => '₾',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'GHS',
                'name' => 'Ghana Cedi',
                'local_name' => 'Ghana Cedi',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'GIP',
                'name' => 'Gibraltar Pound',
                'local_name' => 'Gibraltar Pound',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'GMD',
                'name' => 'Dalasi',
                'local_name' => 'Dalasi',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'GNF',
                'name' => 'Guinean Franc',
                'local_name' => 'Guinean Franc',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'GTQ',
                'name' => 'Guatemalan Quetzal',
                'local_name' => 'Guatemalan Quetzal',
                'flag_emoji' => '🇬🇹',
                'minor_unit' => 2,
                'symbol_prefix' => 'Q',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'GYD',
                'name' => 'Guyana Dollar',
                'local_name' => 'Guyana Dollar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'HKD',
                'name' => 'Hong Kong Dollar',
                'local_name' => 'Hong Kong Dollar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'HNL',
                'name' => 'Honduran lempira',
                'local_name' => 'Honduran Lempira',
                'flag_emoji' => '🇭🇳',
                'minor_unit' => 2,
                'symbol_prefix' => 'L',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'HTG',
                'name' => 'Gourde',
                'local_name' => 'Gourde',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'HUF',
                'name' => 'Hungarian forint',
                'local_name' => 'Hungarian Forint',
                'flag_emoji' => '🇭🇺',
                'minor_unit' => 2,
                'symbol_prefix' => 'Ft',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'IDR',
                'name' => 'Rupiah',
                'local_name' => 'Rupiah',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'ILS',
                'name' => 'New Israeli Sheqel',
                'local_name' => 'New Israeli Sheqel',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'INR',
                'name' => 'Indian Rupee',
                'local_name' => 'Indian Rupee',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'IQD',
                'name' => 'Iraqi Dinar',
                'local_name' => 'Iraqi Dinar',
                'flag_emoji' => null,
                'minor_unit' => 3,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'IRR',
                'name' => 'Iranian Rial',
                'local_name' => 'Iranian Rial',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'ISK',
                'name' => 'Iceland Krona',
                'local_name' => 'Iceland Krona',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'JMD',
                'name' => 'Jamaican Dollar',
                'local_name' => 'Jamaican Dollar',
                'flag_emoji' => '🇯🇲',
                'minor_unit' => 2,
                'symbol_prefix' => 'J$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'JOD',
                'name' => 'Jordanian Dinar',
                'local_name' => 'Jordanian Dinar',
                'flag_emoji' => null,
                'minor_unit' => 3,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'JPY',
                'name' => 'Yen',
                'local_name' => 'Yen',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'KES',
                'name' => 'Kenyan Shilling',
                'local_name' => 'Kenyan Shilling',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'KGS',
                'name' => 'Kyrgyzstani som',
                'local_name' => 'Kyrgyzstani Som',
                'flag_emoji' => '🇰🇬',
                'minor_unit' => 2,
                'symbol_prefix' => 'с',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'KHR',
                'name' => 'Riel',
                'local_name' => 'Riel',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'KMF',
                'name' => 'Comorian Franc ',
                'local_name' => 'Comorian Franc ',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'KPW',
                'name' => 'North Korean Won',
                'local_name' => 'North Korean Won',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'KRW',
                'name' => 'Won',
                'local_name' => 'Won',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'KWD',
                'name' => 'Kuwaiti Dinar',
                'local_name' => 'Kuwaiti Dinar',
                'flag_emoji' => null,
                'minor_unit' => 3,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'KYD',
                'name' => 'Cayman Islands dollar',
                'local_name' => 'Cayman Islands Dollar',
                'flag_emoji' => '🇰🇾',
                'minor_unit' => 2,
                'symbol_prefix' => '$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'KZT',
                'name' => 'Kazakhstani tenge',
                'local_name' => 'Kazakhstani Tenge',
                'flag_emoji' => '🇰🇿',
                'minor_unit' => 2,
                'symbol_prefix' => '₸',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'LAK',
                'name' => 'Lao Kip',
                'local_name' => 'Lao Kip',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'LBP',
                'name' => 'Lebanese Pound',
                'local_name' => 'Lebanese Pound',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'LKR',
                'name' => 'Sri Lanka Rupee',
                'local_name' => 'Sri Lanka Rupee',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'LRD',
                'name' => 'Liberian Dollar',
                'local_name' => 'Liberian Dollar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'LSL',
                'name' => 'Loti',
                'local_name' => 'Loti',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'LYD',
                'name' => 'Libyan Dinar',
                'local_name' => 'Libyan Dinar',
                'flag_emoji' => null,
                'minor_unit' => 3,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MAD',
                'name' => 'Moroccan Dirham',
                'local_name' => 'Moroccan Dirham',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MDL',
                'name' => 'Moldovan leu',
                'local_name' => 'Moldovan Leu',
                'flag_emoji' => '🇲🇩',
                'minor_unit' => 2,
                'symbol_prefix' => 'L',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MGA',
                'name' => 'Malagasy Ariary',
                'local_name' => 'Malagasy Ariary',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MKD',
                'name' => 'Denar',
                'local_name' => 'Denar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MMK',
                'name' => 'Kyat',
                'local_name' => 'Kyat',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MNT',
                'name' => 'Tugrik',
                'local_name' => 'Tugrik',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MOP',
                'name' => 'Pataca',
                'local_name' => 'Pataca',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MRU',
                'name' => 'Ouguiya',
                'local_name' => 'Ouguiya',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MUR',
                'name' => 'Mauritius Rupee',
                'local_name' => 'Mauritius Rupee',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MVR',
                'name' => 'Rufiyaa',
                'local_name' => 'Rufiyaa',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MWK',
                'name' => 'Malawi Kwacha',
                'local_name' => 'Malawi Kwacha',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MXN',
                'name' => 'Mexican Peso',
                'local_name' => 'Mexican Peso',
                'flag_emoji' => '🇲🇽',
                'minor_unit' => 2,
                'symbol_prefix' => '$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MYR',
                'name' => 'Malaysian Ringgit',
                'local_name' => 'Malaysian Ringgit',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'MZN',
                'name' => 'Mozambican Metical',
                'local_name' => 'Mozambican Metical',
                'flag_emoji' => '🇲🇿',
                'minor_unit' => 2,
                'symbol_prefix' => 'MT',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'NAD',
                'name' => 'Namibia Dollar',
                'local_name' => 'Namibia Dollar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'NGN',
                'name' => 'Naira',
                'local_name' => 'Naira',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'NIO',
                'name' => 'Nicaraguan Cordoba',
                'local_name' => 'Nicaraguan Cordoba',
                'flag_emoji' => '🇳🇮',
                'minor_unit' => 2,
                'symbol_prefix' => 'C$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'NOK',
                'name' => 'Norwegian Krone',
                'local_name' => 'Norwegian Krone',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'NPR',
                'name' => 'Nepalese Rupee',
                'local_name' => 'Nepalese Rupee',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'NZD',
                'name' => 'New Zealand Dollar',
                'local_name' => 'New Zealand Dollar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'OMR',
                'name' => 'Rial Omani',
                'local_name' => 'Rial Omani',
                'flag_emoji' => null,
                'minor_unit' => 3,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'PAB',
                'name' => 'Balboa',
                'local_name' => 'Balboa',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'PEN',
                'name' => 'Peruvian Sol',
                'local_name' => 'Peruvian Sol',
                'flag_emoji' => '🇵🇪',
                'minor_unit' => 2,
                'symbol_prefix' => 'S/.',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'PGK',
                'name' => 'Kina',
                'local_name' => 'Kina',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'PHP',
                'name' => 'Philippine Peso',
                'local_name' => 'Philippine Peso',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'PKR',
                'name' => 'Pakistan Rupee',
                'local_name' => 'Pakistan Rupee',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'PLN',
                'name' => 'Polski złoty',
                'local_name' => 'Polski złoty',
                'flag_emoji' => '🇵🇱',
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => 'zł',
            ],
            [
                'currency_code' => 'PYG',
                'name' => 'Paraguayan Guarani',
                'local_name' => 'Paraguayan Guarani',
                'flag_emoji' => '🇵🇾',
                'minor_unit' => 0,
                'symbol_prefix' => '₲',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'QAR',
                'name' => 'Qatari Rial',
                'local_name' => 'Qatari Rial',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'RON',
                'name' => 'Romanian leu',
                'local_name' => 'Romanian Leu',
                'flag_emoji' => '🇷🇴',
                'minor_unit' => 2,
                'symbol_prefix' => 'lei',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'RSD',
                'name' => 'Serbian dinar',
                'local_name' => 'Serbian Dinar',
                'flag_emoji' => '🇷🇸',
                'minor_unit' => 2,
                'symbol_prefix' => 'дин.',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'RUB',
                'name' => 'Russian ruble',
                'local_name' => 'Russian Ruble',
                'flag_emoji' => '🇷🇺',
                'minor_unit' => 2,
                'symbol_prefix' => '₽',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'RWF',
                'name' => 'Rwanda Franc',
                'local_name' => 'Rwanda Franc',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SAR',
                'name' => 'Saudi Riyal',
                'local_name' => 'Saudi Riyal',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SBD',
                'name' => 'Solomon Islands Dollar',
                'local_name' => 'Solomon Islands Dollar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SCR',
                'name' => 'Seychelles Rupee',
                'local_name' => 'Seychelles Rupee',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SDG',
                'name' => 'Sudanese Pound',
                'local_name' => 'Sudanese Pound',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SEK',
                'name' => 'Swedish Krona',
                'local_name' => 'Swedish Krona',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SGD',
                'name' => 'Singapore Dollar',
                'local_name' => 'Singapore Dollar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SHP',
                'name' => 'Saint Helena Pound',
                'local_name' => 'Saint Helena Pound',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SLE',
                'name' => 'Leone',
                'local_name' => 'Leone',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SOS',
                'name' => 'Somali Shilling',
                'local_name' => 'Somali Shilling',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SRD',
                'name' => 'Surinamese dollar',
                'local_name' => 'Surinamese Dollar',
                'flag_emoji' => '🇸🇷',
                'minor_unit' => 2,
                'symbol_prefix' => '$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SSP',
                'name' => 'South Sudanese Pound',
                'local_name' => 'South Sudanese Pound',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'STN',
                'name' => 'Dobra',
                'local_name' => 'Dobra',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SVC',
                'name' => 'El Salvador Colon',
                'local_name' => 'El Salvador Colon',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SYP',
                'name' => 'Syrian Pound',
                'local_name' => 'Syrian Pound',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'SZL',
                'name' => 'Lilangeni',
                'local_name' => 'Lilangeni',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'THB',
                'name' => 'Baht',
                'local_name' => 'Baht',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'TJS',
                'name' => 'Tajikistani somoni',
                'local_name' => 'Tajikistani Somoni',
                'flag_emoji' => '🇹🇯',
                'minor_unit' => 2,
                'symbol_prefix' => 'ЅМ',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'TMT',
                'name' => 'Turkmenistani manat',
                'local_name' => 'Turkmenistani Manat',
                'flag_emoji' => '🇹🇲',
                'minor_unit' => 2,
                'symbol_prefix' => 'm',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'TND',
                'name' => 'Tunisian Dinar',
                'local_name' => 'Tunisian Dinar',
                'flag_emoji' => null,
                'minor_unit' => 3,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'TOP',
                'name' => 'Pa’anga',
                'local_name' => 'Pa’anga',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'TRY',
                'name' => 'Turkish Lira',
                'local_name' => 'Turkish Lira',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'TTD',
                'name' => 'Trinidad and Tobago dollar',
                'local_name' => 'Trinidad and Tobago Dollar',
                'flag_emoji' => '🇹🇹',
                'minor_unit' => 2,
                'symbol_prefix' => 'TT$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'TWD',
                'name' => 'New Taiwan Dollar',
                'local_name' => 'New Taiwan Dollar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'TZS',
                'name' => 'Tanzanian Shilling',
                'local_name' => 'Tanzanian Shilling',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'UAH',
                'name' => 'Ukrainian hryvnia',
                'local_name' => 'Ukrainian Hryvnia',
                'flag_emoji' => '🇺🇦',
                'minor_unit' => 2,
                'symbol_prefix' => '₴',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'UGX',
                'name' => 'Uganda Shilling',
                'local_name' => 'Uganda Shilling',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'USD',
                'name' => 'United States dollar',
                'local_name' => 'US Dollar',
                'flag_emoji' => '🇺🇸',
                'minor_unit' => 2,
                'symbol_prefix' => '$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'UYU',
                'name' => 'Uruguayan Peso',
                'local_name' => 'Uruguayan Peso',
                'flag_emoji' => '🇺🇾',
                'minor_unit' => 2,
                'symbol_prefix' => '$U',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'UYW',
                'name' => 'Unidad Previsional',
                'local_name' => 'Unidad Previsional',
                'flag_emoji' => null,
                'minor_unit' => 4,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'UZS',
                'name' => 'Uzbekistani soʻm',
                'local_name' => 'Uzbekistani Soʻm',
                'flag_emoji' => '🇺🇿',
                'minor_unit' => 2,
                'symbol_prefix' => 'soʻm',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'VED',
                'name' => 'Bolívar Soberano',
                'local_name' => 'Bolívar Soberano',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'VES',
                'name' => 'Bolívar Soberano',
                'local_name' => 'Bolívar Soberano',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'VND',
                'name' => 'Dong',
                'local_name' => 'Dong',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'VUV',
                'name' => 'Vatu',
                'local_name' => 'Vatu',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'WST',
                'name' => 'Tala',
                'local_name' => 'Tala',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'XAD',
                'name' => 'Arab Accounting Dinar',
                'local_name' => 'Arab Accounting Dinar',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'XAF',
                'name' => 'CFA Franc BEAC',
                'local_name' => 'CFA Franc BEAC',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'XBA',
                'name' => 'Bond Markets Unit European Composite Unit (EURCO)',
                'local_name' => 'Bond Markets Unit European Composite Unit (EURCO)',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'XBB',
                'name' => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
                'local_name' => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'XBC',
                'name' => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
                'local_name' => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'XBD',
                'name' => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
                'local_name' => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'XCD',
                'name' => 'East Caribbean dollar',
                'local_name' => 'East Caribbean Dollar',
                'flag_emoji' => '🇦🇬',
                'minor_unit' => 2,
                'symbol_prefix' => 'EC$',
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'XCG',
                'name' => 'Caribbean Guilder',
                'local_name' => 'Caribbean Guilder',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'XOF',
                'name' => 'CFA Franc BCEAO',
                'local_name' => 'CFA Franc BCEAO',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'XPF',
                'name' => 'CFP Franc',
                'local_name' => 'CFP Franc',
                'flag_emoji' => null,
                'minor_unit' => 0,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'YER',
                'name' => 'Yemeni Rial',
                'local_name' => 'Yemeni Rial',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'ZAR',
                'name' => 'Rand',
                'local_name' => 'Rand',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'ZMW',
                'name' => 'Zambian Kwacha',
                'local_name' => 'Zambian Kwacha',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
            [
                'currency_code' => 'ZWG',
                'name' => 'Zimbabwe Gold',
                'local_name' => 'Zimbabwe Gold',
                'flag_emoji' => null,
                'minor_unit' => 2,
                'symbol_prefix' => null,
                'symbol_suffix' => null,
            ],
        ];

        $currencies = array_map(
            static function (array $currency) use ($timestamp): array {
                return [
                    ...$currency,
                    'is_active' => true,
                    'created_at' => $timestamp,
                    'updated_at' => $timestamp,
                ];
            },
            $currencies
        );

        DB::table('currencies')->upsert(
            $currencies,
            ['currency_code'],
            [
                'name',
                'local_name',
                'flag_emoji',
                'minor_unit',
                'symbol_prefix',
                'symbol_suffix',
                'is_active',
                'updated_at',
            ]
        );
    }
}
